### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by vis23** [mills32/Little-Game-Engine-for-VGA#2]
Hi
Lib looks great, having trouble running all the demos, missing some files 
gfx/wmap.tmx, music/adlib/menu.imf, music/adlib/faces.imf, gfx/puz.tmx, gfx/puz1.tmx, music/adlib/save.imf

I guess I could have renamed some music files but I wanted to get the intended effect. Obviously the missing map files are a little more vital.

Thank you

**Comment by mills32** [comment]
Sorry, it took me too long to make some parts work OK, so this is just a back up for the moment, (just in case I had some trouble with my PC). I upload everything new I test, so the asests are a mess, I'm going to make a simpler version and upload the missing files.

**Comment by vis23** [comment]
Thank you for your response. I have been enjoying exploring your code.

**Comment by mills32** [comment]
I think it's solved.

**Comment by vis23** [comment]
Great, thanks! I will try the puzzles, thanks again, and again I am finding
the code very helpful to learn from for my own project.

Regards
Vis
